# Generated by Django 5.1.2 on 2024-11-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_banner_homemessage_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('pattern', models.CharField(default='', max_length=100)),
                ('number', models.CharField(default='', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
