# Generated by Django 5.1.2 on 2024-11-02 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Avatars/')),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BattlePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('type', models.CharField(choices=[('add_task', 'Add Task'), ('complete_task', 'Complete Task'), ('open_app', 'Open App'), ('min_time', 'Min Time'), ('different_lesson', 'Different Lesson')], default='add_task', max_length=50)),
                ('xp', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battle_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.battlepass')),
            ],
        ),
        migrations.CreateModel(
            name='DailyChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('coin', 'Coin'), ('avatar', 'Avatar')], default='coin', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Game.avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('level', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battle_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.battlepass')),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Game.reward')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('type', models.CharField(choices=[('min_time', 'MinTime'), ('every_day_enter', 'Every Day Enter'), ('every_day_add_task', 'Every Day Add Task'), ('progress', 'Progress')], default='min_time', max_length=50)),
                ('xp', models.IntegerField()),
                ('value', models.IntegerField(default=0)),
                ('battle_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.battlepass')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weekly_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.weeklychallenge')),
            ],
        ),
        migrations.CreateModel(
            name='BattlePassParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battle_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.battlepass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'battle_pass')},
            },
        ),
    ]
