# Generated by Django 5.1.2 on 2024-11-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='type',
            field=models.CharField(choices=[('gpt', 'GPT'), ('gemini', 'Gemini')], default='gemini', max_length=10),
        ),
    ]
