# Generated by Django 5.1.2 on 2024-11-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0003_prompt_chat_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
